AlarmManager: Handle google and system apps alarm denials [2/2]
[someone5678]
* Moved into PixelPropsUtils
* Use RRO

Initial package lists:
com.google.android.gms
com.google.android.keep
com.google.android.deskclock
com.android.deskclock

java.lang.SecurityException: Caller com.google.android.gms needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:359)
	at android.app.AlarmManager.setImpl(AlarmManager.java:948)
	at android.app.AlarmManager.setImpl(AlarmManager.java:908)
	at android.app.AlarmManager.set(AlarmManager.java:818)
	at usv.k(:com.google.android.gms@213314046@21.33.14 (150400-395723304):1)
	at usv.o(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
	at usv.e(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
	at com.google.android.contextmanager.controller.EventHandler$AlarmSetter.c(:com.google.android.gms@213314046@21.33.14 (150400-395723304):8)
	at exr.d(:com.google.android.gms@213314046@21.33.14 (150400-395723304):3)
	at ext.l(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
	at evr.a(:com.google.android.gms@213314046@21.33.14 (150400-395723304):143)
	at ext.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
	at exp.handleMessage(:com.google.android.gms@213314046@21.33.14 (150400-395723304):3)
	at uwe.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
	at uwo.c(:com.google.android.gms@213314046@21.33.14 (150400-395723304):6)
	at uwo.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at vcm.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
	at java.lang.Thread.run(Thread.java:920)

Sqaushed commit:
	apex: Prevent illegal state exception caused by GMS concurrent alarms

	08-08 06:03:34.372  1683  9319 W AlarmManager: Maximum limit of concurrent alarms 500 reached for uid: u0a380, callingPackage: com.google.android.gms
	08-08 06:03:34.375 25269 25323 E AlarmManager: unable to set alarm "NetworkLocationLocator" (IllegalStateException)
	08-08 06:03:34.375 25269 25323 E AlarmManager: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a380, callingPackage: com.google.android.gms
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Parcel.createException(Parcel.java:2999)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Parcel.readException(Parcel.java:2982)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Parcel.readException(Parcel.java:2924)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:310)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.app.AlarmManager.setImpl(AlarmManager.java:1009)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.app.AlarmManager.setExact(AlarmManager.java:949)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at awkh.h(:com.google.android.gms@232617044@23.26.17 (190400-551657477):79)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at awju.a(:com.google.android.gms@232617044@23.26.17 (190400-551657477):49)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dclx.e(:com.google.android.gms@232617044@23.26.17 (190400-551657477):120)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dchy.c(:com.google.android.gms@232617044@23.26.17 (190400-551657477):55)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dchy.f(:com.google.android.gms@232617044@23.26.17 (190400-551657477):860)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dcsn.b(:com.google.android.gms@232617044@23.26.17 (190400-551657477):1653)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dcsk.b(:com.google.android.gms@232617044@23.26.17 (190400-551657477):22)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dcle.c(:com.google.android.gms@232617044@23.26.17 (190400-551657477):79)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dclv.run(:com.google.android.gms@232617044@23.26.17 (190400-551657477):9)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at dcla.handleMessage(:com.google.android.gms@232617044@23.26.17 (190400-551657477):93)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at awsu.li(:com.google.android.gms@232617044@23.26.17 (190400-551657477):1)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at awsu.dispatchMessage(:com.google.android.gms@232617044@23.26.17 (190400-551657477):143)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Looper.loopOnce(Looper.java:201)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Looper.loop(Looper.java:288)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
	08-08 06:03:34.375 25269 25323 E AlarmManager: Caused by: android.os.RemoteException: Remote stack trace:
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at com.android.server.alarm.AlarmManagerService.setImpl(AlarmManagerService.java:2310)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2952)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:182)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
	08-08 06:03:34.375 25269 25323 E AlarmManager: 	at android.os.Binder.execTransact(Binder.java:1244)

	Change-Id: I9d95d8f999e29f5193f1805a17c937168b5d971c
	Signed-off-by: minaripenguin <minaripenguin@users.noreply.github.com>

Change-Id: I6a179661a3da33cba54cbc07c48adcebcaf008a8
Co-authored-by: Danny Lin <danny@kdrag0n.dev>
Co-authored-by: minaripenguin <minaripenguin@users.noreply.github.com>
Signed-off-by: someone5678 <59456192+someone5678@users.noreply.github.com>